import { describe, expect, it } from "vitest";
import { extractHealthScore, formatHealthScore } from "./aiScore";

describe("aiScore", () => {
  it("extracts the financial score generated by the AI", () => {
    expect(extractHealthScore("1. Score Financeiro: 3/10")).toBe(3);
    expect(formatHealthScore("Score Financeiro: 8,4/10")).toBe("8.4");
  });

  it("supports health score wording and clamps unexpected values", () => {
    expect(formatHealthScore("Health Score: 12/10")).toBe("10.0");
  });

  it("returns a placeholder when no score is available", () => {
    expect(extractHealthScore("Analise sem nota numerica.")).toBeNull();
    expect(formatHealthScore(undefined)).toBe("--");
  });
});
